# Generated by Django 5.1.5 on 2025-01-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_of_date', models.DateField()),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='student_images/')),
            ],
        ),
    ]
