# Generated by Django 5.1.4 on 2024-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='student_images/')),
            ],
        ),
    ]
