# Generated by Django 5.1.4 on 2024-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(related_name='groups', to='students.student'),
        ),
    ]
