# Generated by Django 5.1.5 on 2025-01-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_students_group_students'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.student'),
        ),
    ]
