# Generated by Django 5.1.5 on 2025-01-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_students_alter_group_teacher_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.student'),
        ),
    ]
