# Generated by Django 5.1.5 on 2025-01-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_students_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
    ]
